chore: maintenance of dependencies, bots, build scripts, and linting
decentralized-identity/did-resolver pull request #92
Opened 2021-06-24 10:52 UTC by mirceanis

This PR is part of a greater effort to reduce the maintenance burden by using a standard set of scripts and tools on all repositories currently in maintenance.

Changes included here:
* switch from circleci to gh actions
  * circleci checks will show as failed until we disable the circleci build
* reschedule renovate bot for less noise
* adjust stalebot config
* revise and update dependencies and build scripts
* use eslint and fix errors
* adjust linter and compiler configs
* reformat code
* add `publicKeyMultibase` to `VerificationMethod` definition

2021-06-28 10:57 UTC, rado0x54 requested changes

2021-06-28 10:57 UTC, rado0x54 commented on package.json
> +  "module": "lib/resolver.module.js",
I think now main and module keywords are correctly used (CJS / ESM)! 👍🏻

2021-06-28 13:29 UTC, mirceanis commented on package.json
> +  "umd:main": "lib/resolver.umd.js",
I followed some guides from `microbundle` but I don't know when these are used, actually.
I can remove them.

2021-06-29 05:34 UTC, merged

2021-09-27 14:39 UTC, yhuard commented
Hi @mirceanis! Do you plan to release a new version of the lib soon? There are changes in this PR that I would like to use :) (like the new `publicKeyMultibase` prop on VerificationMethod). Thanks!

2021-09-27 15:44 UTC, mirceanis commented
@yhuard I just did, see version 3.1.1 :)

2021-09-27 16:07 UTC, yhuard commented
Excellent! Thank you very much 🙇